#!/bin/sh

if [ ! "$(whoami)" = root ] && [ ! -e ~/.ssh/id_rsa_"$(hostname -s)".pub ] ; then
    echo "" && ssh-keygen -t rsa -b 4096 -C "$(whoami)@$(hostname -s)" -f "${HOME}"/.ssh/id_rsa_"$(hostname -s)"
    echo ""
    echo "Copy id_rsa_$(hostname -s).pub to gitea, gitolite-admin, gitolite1-admin & gitolite2-admin. Restart bootstrap once completed..."
    echo ""
    exit 1
fi

if [ "$(uname)" = Darwin ] ; then
    [ -r /usr/local/bin/brew ] && BIN="/usr/local/bin"
    [ -r /opt/homebrew/bin/brew ] && BIN="/opt/homebrew/bin"
    "$BIN/brew" doctor || true
    "$BIN/brew" install mr vcsh
# arch
elif [ "$(uname)" = Linux ] && [ -f /etc/arch-release ] ; then
    ./arch.sh
    BIN="/usr/bin"
    if [ ! -d "$HOME/.config/vcsh/repo.d/dotfiles.git" ] ; then
        mv ~/.bash_profile ~/.bash_profile.bak
        mv ~/.bashrc ~/.bashrc.bak
    fi
elif [ "$(hostname -s)" = unraid ] ; then
    BIN="/usr/local/bin"
    if [ ! -d "$HOME/.config/vcsh/repo.d/dotfiles.git" ] ; then
        mv ~/.bash_profile ~/.bash_profile.bak
    fi
    if [ "$(whoami)" = root ] ; then
        cd /etc/bash_completion.d && wget -N https://raw.githubusercontent.com/git/git/v2.14.1/contrib/completion/git-completion.bash
        cd /usr/bin && ln -sf 'vim' 'vi'
        mkdir -p /usr/local/src
        cd /usr/local/src || exit 2
        if [ ! -d "vcsh/.git" ] ; then
            git clone https://github.com/RichiH/vcsh.git
            cd /usr/local/bin && ln -sf /usr/local/src/vcsh/vcsh
        fi
        cd /usr/local/src || exit 3
        if [ ! -d "myrepos/.git" ] ; then
            git clone https://git.joeyh.name/git/myrepos.git/
            cd /usr/local/bin && ln -sf /usr/local/src/myrepos/mr
        fi
        cd /usr/local/src || exit 4
        if [ ! -d "colordiff/.git" ] ; then
            git clone https://github.com/daveewart/colordiff.git
            cd /usr/local/bin && ln -sf /usr/local/src/colordiff/colordiff.pl colordiff
        fi
    fi
elif [ "$(uname)" = Linux ] ; then
    BIN="/usr/bin"
    if [ ! -d "$HOME/.config/vcsh/repo.d/dotfiles.git" ] ; then
        mv ~/.profile ~/.profile.bak
        mv ~/.bashrc ~/.bashrc.bak
    fi
    if [ "$(whoami)" = root ] ; then
        apt-get update && apt-get --yes install etckeeper keychain myrepos sudo vcsh vim zsh
        if [ ! -d /etc/.git ] ; then
            pushd /etc || exit 5
            sudo etckeeper init
            sudo git config user.email "root@$(hostname)"
            sudo git config user.name "root"
            sudo etckeeper commit 'Initial commit'
            popd
        fi
    else
        command -v git >/dev/null 2>&1 && \
          command -v mr >/dev/null 2>&1 && \
          command -v sudo >/dev/null 2>&1 && \
          command -v vcsh >/dev/null 2>&1 && \
          command -v vim >/dev/null 2>&1 && \
          command -v zsh >/dev/null 2>&1 || \
          { echo "" ; echo "run bootstrap.sh as root first" ; echo "" ; exit 6 ; }
    fi
    if [ ! -f /etc/arch-release ] ; then
        if [ ! -d "$HOME/.config/vcsh/repo.d/apt.git" ] ; then
            "$BIN/vcsh" clone "https://github.com/tomhoover/apt-vcsh.git" "apt"
            "$BIN/vcsh" apt remote add gitea gitea:tom/apt-vcsh.git
            "$BIN/vcsh" apt remote add gitolite1 gitolite1:tom/apt-vcsh.git
            "$BIN/vcsh" apt remote add gitolite2 gitolite2:tom/apt-vcsh.git
        fi
        # sudo aptitude install "$(cat ~/.config/apt/installed)"
        # sudo apt-mark manual $(cat ~/.config/apt/installed) 	# this line is probably not needed, but added for good measure
    fi
fi

REPOS="dotfiles
git
mr"
while read -r REPO; do
    if [ ! -d "$HOME/.config/vcsh/repo.d/$REPO.git" ] ; then
        "$BIN/vcsh" clone "https://github.com/tomhoover/${REPO}-vcsh.git" "${REPO}"
        "$BIN/vcsh ${REPO}" remote add gitea         "gitea:tom/${REPO}-vcsh.git"
        "$BIN/vcsh ${REPO}" remote add gitolite1 "gitolite1:tom/${REPO}-vcsh.git"
        "$BIN/vcsh ${REPO}" remote add gitolite2 "gitolite2:tom/${REPO}-vcsh.git"
    fi
done <<EOF
$REPOS
EOF

echo ""
cd && "$BIN/mr" -m -j 1 up
cd && [ -f .config/crontab/`hostname -s`.`whoami`.crontab ] && crontab .config/crontab/`hostname -s`.`whoami`.crontab || true
echo ""
echo "chsh -s $(which zsh)"
echo ""
echo "To install 'private-vcsh' repo:"
# echo "  mv ~/.gitconfig ~/.gitconfig.bak"
echo "  vcsh clone 'gitea:tom/private-vcsh.git' 'private' && vcsh private remote add gitolite1 gitolite1:private-vcsh.git && vcsh private remote add gitolite2 gitolite2:private-vcsh.git"
echo ""
echo "logout and login to re-read configuration"
