#!/bin/sh

if [ "$(uname)" = Darwin ] ; then
    BIN="/usr/local/bin"
    brew doctor || true
    brew install mr vcsh
    if [ ! -d "$HOME/.config/vcsh/repo.d/private.git" ] ; then
        mv ~/.gitconfig ~/.gitconfig.bak
        echo ""
        echo "enter password for manuel:"
        "$BIN/vcsh" clone "manuel.local:git/private-vcsh.git" "private"
    fi
fi

if [ "$(hostname -s)" = unraid ] ; then
    BIN="/usr/local/bin"
    if [ ! -d "$HOME/.config/vcsh/repo.d/dotfiles.git" ] ; then
        mv ~/.bash_profile ~/.bash_profile.bak
    fi
    if [ "$(whoami)" = root ] ; then
        cd /usr/bin && ln -sf 'vim' 'vi'
        mkdir -p /usr/local/src
        cd /usr/local/src || exit
        if [ ! -d "vcsh/.git" ] ; then
            git clone https://github.com/RichiH/vcsh.git
            cd /usr/local/bin && ln -sf /usr/local/src/vcsh/vcsh
        fi
        cd /usr/local/src || exit
        if [ ! -d "myrepos/.git" ] ; then
            git clone https://git.joeyh.name/git/myrepos.git/
            cd /usr/local/bin && ln -sf /usr/local/src/myrepos/mr
        fi
        cd /usr/local/src || exit
        if [ ! -d "colordiff/.git" ] ; then
            git clone https://github.com/daveewart/colordiff.git
            cd /usr/local/bin && ln -sf /usr/local/src/colordiff/colordiff.pl colordiff
        fi
    fi
elif [ "$(uname)" = Linux ] ; then
    BIN="/usr/bin"
    sudo apt-get update && sudo apt-get install git mr vcsh etckeeper
fi

REPOS="dotfiles
git
mr"
while read -r REPO; do
    if [ ! -d "$HOME/.config/vcsh/repo.d/$REPO.git" ] ; then
        "$BIN/vcsh" clone "https://github.com/tomhoover/$REPO-vcsh.git" "$REPO"
    fi
done <<EOF
$REPOS
EOF

if [ "$(uname)" = Linux ] && [ ! "$(hostname -s)" = unraid ] ; then
    if [ ! -d "$HOME/.config/vcsh/repo.d/apt.git" ] ; then
        "$BIN/vcsh" clone "https://github.com/tomhoover/apt-vcsh.git" "apt"
    fi
    # sudo aptitude install "$(cat ~/.config/apt/installed)"
    # sudo apt-mark manual $(cat ~/.config/apt/installed) 	# this line is probably not needed, but added for good measure
fi

if [ ! -d "$HOME/.spf13-vim-3" ] ; then
    cd && curl http://j.mp/spf13-vim3 -L -o - | sh
#    mv ~/.vimrc.local ~/.vimrc.local.bak
else
    cd ~/.spf13-vim-3 || exit
    git pull
    vim +BundleInstall! +BundleClean +q
fi

echo ""
cd && "$BIN/mr" -m up
echo ""
echo "chsh -s $(which zsh)"
echo ""
echo "logout and login to re-read configuration"
