#!/usr/bin/env bash

# Run all dotfiles installers.
# https://github.com/MartinHeinz/dotfiles/blob/master/script/install

set -e

# add python build dependencies for debian/ubuntu
command -v apt >/dev/null 2>&1 && \
    ( command -v gcc >/dev/null 2>&1 && \
      command -v make >/dev/null 2>&1 && \
      command -v curl >/dev/null 2>&1 || \
      sudo apt --yes install build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
      libsqlite3-dev curl libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev )

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | sort | while read installer ; do
    program=$(echo $installer | sed -e 's/^\.\///' -e 's/^0-//' -e 's/\/.*$//')
    if command -v ${program} >/dev/null 2>&1 ; then continue; fi
    echo "Installing ${program}..."
    if [ $program = 0-pyenv ]; then
        command -v pyenv >/dev/null 2>&1 || sh -c "${installer}"
    elif [ $program = direnv ]; then
        sh -c "bin_path=~/.local/bin ${installer}"
    else
        sh -c "${installer}" || exit 99
    fi
done
