[[mgr.prepend_keymap]]
on = ["c", "p"]
run = "plugin command"
desc = "Open command palette"

[[mgr.prepend_keymap]]
on = ["<A-j>", "i"]
run = "plugin dupes interactive"
desc = "Run dupes interactive"

[[mgr.prepend_keymap]]
on = ["<A-j>", "o"]
run = "plugin dupes override"
desc = "Run dupes override"

[[mgr.prepend_keymap]]
on = ["<A-j>", "d"]
run = "plugin dupes dry"
desc = "Run dupes dry"

[[mgr.prepend_keymap]]
on = ["<A-j>", "a"]
run = "plugin dupes apply"
desc = "Run dupes apply"

# [[mgr.prepend_keymap]]
# on = ["<A-J>", "c"]
# run = "plugin dupes custom"
# desc = "Run dupes custom"
