[settings]
# activate_aggressive = false
experimental = true
hook_env.chpwd_only = true
idiomatic_version_file_enable_tools = ["python"]
# python_compile = true

## setting the following will enable reading .env everywhere
# env_file = ".env"

## to only read .env from a particular project directory, include the following within the project's [.]mise.[local.]toml file
# [env]
# _.file = '.env'

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[env]
# Use default profile
_.fnox-env = { tools = true }
# Use production profile
# _.fnox-env = { tools = true, profile = "production" }

_.path = [
    "~/bin",
    "~/.opencode/bin",
    "~/.local/bin"
]

# Git credentials
# Not included in public .gitconfig, to prevent people from accidentally committing under my name
GIT_AUTHOR_NAME = "Tom Hoover"
GIT_AUTHOR_EMAIL = "tom@hisword.net"
GIT_COMMITTER_NAME = "Tom Hoover"
GIT_COMMITTER_EMAIL = "tom@hisword.net"

[tools]
# "go:github.com/containerscrew/tftools" = "latest"
# "pipx:flake8" = "latest"
# "pipx:isort" = "latest"
# "pipx:pylint" = "latest"
"aqua:runkids/skillshare" = "latest"
"github:anomalyco/opencode" = "latest"
"pipx:audible-cli" = "latest"
"pipx:ipython" = "latest"
"pipx:tmuxp" = "latest"
# bats = "latest"
# black = "latest"
# claude = "latest"
# cookiecutter = "latest"
# pipx = "latest"
# pre-commit = "latest"
# terraform = "latest"
# tflint = "latest"
# tfsec = "latest"
bat = "latest"
codex = "latest"
copier = "latest"
fd = "latest"
fnox = "latest"
gemini = "latest"
hyperfine = "latest"
node = "latest"
pi = "latest"
prek = "latest"
python = ["3.10", "3.11", "3.12", "3.13"]
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
uv = "latest"

[tasks.docker]
run = "docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest"

[tasks.pin]
run = "mise use --pin $(mise registry | fzf --multi | awk '{print $2}')"
